[global]
error_log = /dev/stderr;

[www]
listen = /run/php-fpm.sock;
pm.status_path = /fpm-status;
pm = static;
pm.max_children = 200;
pm.max_requests = 10000;
pm.process_idle_timeout = 10s;
clear_env = no;
catch_workers_output = yes;
decorate_workers_output = no;
ping.path = /fpm-ping;
listen.backlog = 65536;