worker_processes auto;
error_log stderr warn;
pid /run/nginx.pid;

events {
    worker_connections 8192;
    use epoll;
}

http {
    include mime.types;
    default_type application/octet-stream;

    log_format main_res '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for" '
    '$request_time $upstream_response_time $pipe $upstream_cache_status';

    error_log stderr warn;
    access_log /dev/stdout main_res;

    tcp_nopush on;

    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 32 16k;
    gzip_http_version 1.1;
    gzip_min_length 250;
    gzip_types image/jpeg image/bmp image/svg+xml text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript image/x-icon;

    client_body_timeout 12;
    client_header_timeout 12;
    keepalive_timeout 15;
    send_timeout 10;

    client_body_buffer_size 10K;
    client_header_buffer_size 1k;
    large_client_header_buffers 4 4k;
    client_max_body_size 5M;

    client_body_temp_path /tmp/client_temp;
    proxy_temp_path /tmp/proxy_temp_path;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;

    server {
        listen 8080;
        server_name _;

        sendfile off;
        absolute_redirect off;

        root /var/www/html;
        index index.php;

        location ~ \.php$ {
            try_files $uri @rewrite =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/var/run/php-fpm.sock;
            fastcgi_intercept_errors on;
            fastcgi_read_timeout 6000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        location /thumb_handler.php/ {
            include fastcgi_params;
            fastcgi_read_timeout 60s;
            fastcgi_param SCRIPT_FILENAME $document_root/thumb_handler.php;
            fastcgi_pass unix:/var/run/php-fpm.sock;
        }

        location @thumb {
            rewrite ^/images/thumb/([0-9a-f]/[0-9a-f][0-9a-f]/([^/]+)/[^/]*([0-9]+)px-.*)$ /thumb_handler.php/$1;
            rewrite ^/images/thumb/(archive/[0-9a-f]/[0-9a-f][0-9a-f]/([^/]+)/[^/]*([0-9]+)px-.*)$ /thumb_handler.php/$1;
        }

        location /images/ {
            add_header 'Access-Control-Allow-Origin' 'gbf.wiki' always;
            alias /var/www/html/images/;
            location ~ ^/images/thumb/(archive/)?[0-9a-f]/[0-9a-f][0-9a-f]/([^/]+)/[^/]*([0-9]+)px-.*$ {
                try_files $uri $uri/ @thumb;
            }
        }

        location /extensions/ {
            alias /var/www/html/extensions/;
        }

        location /skins/ {
            alias /var/www/html/skins/;
        }

        location /resources/ {
            alias /var/www/html/resources/;
        }

        location @rewrite {
            rewrite ^/(.*)$ /index.php;
        }

        location ~* /(?:docs|extensions|includes|cache|languages|maintenance|mw-config|serialized|skins|tests|vendor|images)/.*.php$ {
            deny all;
        }

        location ~ /.(svn|git)(/|$) {
            deny all;
        }

        location ~ /rest.php {
            try_files $uri $uri/ /rest.php?$args;
        }

        location / {
            rewrite ^/(?<pagename>.*)$ /index.php;
            try_files $uri $uri/ @rewrite;
            error_page 403 /banned.html;
            error_page 502 /502.html;
        }
    }
}